# Oracle Database Configuration
oracle_ods:
  dsn: "oci-db-prod-phcte-scan.db.vcn193.oraclevcn.com:1521/odsedwp.db.vcn193.oraclevcn.com"
  user: AIUSER

oracle_clon:
  dsn: "oci-db-prod-phcte-scan.db.vcn193.oraclevcn.com:1521/clon.db.vcn193.oraclevcn.com"
  user: RPTUSER

datasource_mapping:
  ODS: "oracle_ods"
  PROD: "oracle_clon"
  CLON: "oracle_clon"

# # Databricks Configuration
# databricks:
#   default_catalog: "scad_reporting_dev"
#   default_schema: "default"

# # Project Configuration
# project:
#   mappings_file: "mappings.csv"
#   directory_paths:
#     output:
#       path: "output"
#       is_dir: True
#       create: True
